name: Feature Request
description: Suggest a new feature or enhancement for LeanCLR
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for your suggestion! Please describe the feature you'd like to see in LeanCLR.

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: What area of LeanCLR does this feature relate to?
      options:
        - Runtime Core (VM, Type System)
        - IL/IR Interpreter
        - AOT Compiler
        - Garbage Collection
        - Internal Calls (icalls)
        - P/Invoke
        - Multi-threading
        - ECMA-335 Compliance
        - Platform Support
        - Tooling (lean CLI)
        - Documentation
        - Testing Framework
        - Other
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: "A clear description of the problem. Ex: I'm always frustrated when..."

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like
      placeholder: A clear and concise description of what you want to happen
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered

  - type: textarea
    id: usecase
    attributes:
      label: Use Case
      description: Describe your use case for this feature
      placeholder: |
        - Platform: WebAssembly / Mobile / Desktop
        - Scenario: Game development / Embedded system / etc.

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, mockups, or examples about the feature request
